# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OWF Learn / QGIS
pages:
- Home: index.md
- Overview: overview.md
- Install QGIS: install-qgis.md
- 'Map Configuration':
  - Overview: 'map-config/overview.md'
- 'Map Layers':
  - Overview: 'map-layers/overview.md'
  - 'GeoJSON (vector)': 'map-layers/vector-geojson.md'
- 'Raster automation using GDAL Tools':
  - Overview: 'gdal/overview.md'
- 'Vector automation using OGR Tools':
  - Overview: 'ogr/overview.md'
theme: readthedocs
repo_url:  https://github.com/OpenWaterFoundation/owf-learn-qgis
site_description:  Open Water Foundation Learn QGIS
site_author:  Open Water Foundation
site_favicon:  OWF-Logo-Favicon-32x32.png
copyright:  Copyright Open Water Foundation
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
